// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWQjuI5yNiXhC3fisCxYAJG9QTlpZWEss',
    appId: '1:903713236844:web:9784b00dbce9058bd77549',
    messagingSenderId: '903713236844',
    projectId: 'prog-mob-3ec1b',
    authDomain: 'prog-mob-3ec1b.firebaseapp.com',
    storageBucket: 'prog-mob-3ec1b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC8kpkNME9naDz6qJFB5VgvJorbqZMQaE',
    appId: '1:903713236844:android:19ec208a8f37dbf2d77549',
    messagingSenderId: '903713236844',
    projectId: 'prog-mob-3ec1b',
    storageBucket: 'prog-mob-3ec1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC20VH0fUjIJXDFZDjxjItiFSEPIgjT84',
    appId: '1:903713236844:ios:d4367d61a17e7505d77549',
    messagingSenderId: '903713236844',
    projectId: 'prog-mob-3ec1b',
    storageBucket: 'prog-mob-3ec1b.firebasestorage.app',
    iosBundleId: 'com.example.tpArisMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC20VH0fUjIJXDFZDjxjItiFSEPIgjT84',
    appId: '1:903713236844:ios:d4367d61a17e7505d77549',
    messagingSenderId: '903713236844',
    projectId: 'prog-mob-3ec1b',
    storageBucket: 'prog-mob-3ec1b.firebasestorage.app',
    iosBundleId: 'com.example.tpArisMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWQjuI5yNiXhC3fisCxYAJG9QTlpZWEss',
    appId: '1:903713236844:web:0423b90e59156ec8d77549',
    messagingSenderId: '903713236844',
    projectId: 'prog-mob-3ec1b',
    authDomain: 'prog-mob-3ec1b.firebaseapp.com',
    storageBucket: 'prog-mob-3ec1b.firebasestorage.app',
  );
}
